[package]
name = "lib-schemas"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true}
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde", "v7", "v4"] }

[dev-dependencies]
serde_json = { workspace = true }

[features]
skuffen = []
default = []
