[package]
name = "lib-nats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-nats = { version = "0.40.0" }
futures = { version = "0.3.31", default-features = false }
secrecy = "0.10.3"
