[package]
name = "lib-mt-ansatte"
version = "0.1.0"
edition = "2024"

[dependencies]
async-nats = "0.50.0"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
uuid = { workspace = true }
